name: Run test suite

on:
  pull_request:

  push:
    branches:
      - main

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        # NOTE: If bumping the minimum Python version here, also do it in
        # ruff.toml, setup.py and other CI files as well.

        # test with oldest and latest supported Python versions
        python-version: ["3.10", "3.13"]

      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Restore UV environment
        run: cp production.uv.lock uv.lock

      - name: Install dev requirements
        run: |
          uv sync --extra dev --frozen

      - name: Run test suite
        run: |
          set -o pipefail
          uv run --no-sync pytest \
            --cov-report=term-missing:skip-covered \
            --cov-report=xml:coverage.xml \
            --cov=tesseract_torch

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: pasteurlabs/tesseract-torch
          files: coverage*.xml
          fail_ci_if_error: true

  all-ok:
    if: always()
    needs: [tests]

    runs-on: ubuntu-latest

    steps:
      - name: Check for errors
        run: |
          if [[ "${{ needs.tests.result }}" != "success" && "${{ needs.tests.result }}" != "skipped" ]]; then
            echo "Tests failed"
            exit 1
          fi

          echo "All tests passed!"
